Show message when comments are turned off
omarroth/invidious pull request #4051
Opened 2023-08-14 07:02 UTC by syeopite

Fixes: #1092
I want to be awarded the bounty associated to the issue this PR is fixing.

![comments](https://github.com/iv-org/invidious/assets/70992037/73a83540-2fc4-491b-959d-0b0a317833bb)

I've also added a message for when comments are disabled via Invidious config.

2023-08-23 15:21 UTC, Fijxu commented
Tested and checked, works without problems. I haven't tested it on production but it works as is, no need to change settings. However i wasn't able to find the invidious config related to "added a message for when comments are disabled via Invidious config" but it works. Comments on videos WITHOUT comments disabled are displayed.

If anyone wants to test this in a debug/test instance it can be easily merged using this commands:

```sh
$ git fetch origin pull/4051/head:show-comments-turned-off-message
$ git merge show-comments-turned-off-message
$ make
```

![image](https://github.com/iv-org/invidious/assets/61166695/d04e9d03-8fc1-4585-ac2e-25aa5f868557)

*I would add translations for `es.json` in this pull request but I don't know how to propose changes to a pull request*

2023-08-23 19:59 UTC, syeopite commented
> However i wasn't able to find the invidious config related to "added a message for when

Oops. I shouldn't have used the word config there. I meant when comments are disabled in Invidious's preferences.  

See https://github.com/iv-org/invidious/issues/2585#issuecomment-1686633019 for how to do so. Its not very clear in the UI. 

> _I would add translations for es.json in this pull request but I don't know how to propose changes to a pull request_

Unfortunately Github only lets you suggest changes on lines near changes that occurred within the PR. If you'd like to add translations feel free to make a PR to the `show-comments-turned-off-message` branch on my fork here https://github.com/syeopite/invidious. It should get automatically included in this PR once merged.

2023-09-17 13:04 UTC, SamantazFox requested changes

2023-09-17 13:04 UTC, SamantazFox commented on assets/js/watch.js
> +            </div>`;
```suggestion
                <p><b><a href="javascript:void(0)" data-comments="reddit" id="try-reddit-comments-link">
                    ${video_data.youtube_comments_disabled_try_reddit}
                </a></b></p>
            </div>`;
```

2023-09-17 13:04 UTC, SamantazFox commented on assets/js/watch.js
> +            </div>`;
This can be condensed a bit ^^
Also, I'm not sure about `javacsript:void(0)` links (See #769)

2024-12-02 14:15 UTC, Anjolao commented
The Backend on invidious is not working. Is there a way to fix the backends?

2025-05-09 04:21 UTC, Fijxu commented
Merged into my instance as it works fine

![image](https://github.com/user-attachments/assets/e55a0088-b6cd-469b-a2fc-b892ab6cdfab)

2025-05-09 07:09 UTC, unixfox reviewed
Good for merging

2025-05-09 07:09 UTC, unixfox approved these changes

2025-08-28 00:19 UTC, Fijxu requested changes

2025-08-28 00:19 UTC, Fijxu commented on src/invidious/videos/parser.cr
> +    section = primary_results.as_a.find(&.dig?("itemSectionRenderer", "sectionIdentifier").== "comments-entry-point")
`comments-entry-point` has changed to `comment-item-section`

```suggestion
    section = primary_results.as_a.find(&.dig?("itemSectionRenderer", "sectionIdentifier").== "comment-item-section")
```

2026-06-13 09:55 UTC, Ghostofcaldera commented
Hi! I've analyzed this issue and think I can help:
**Root cause**: Simple code update to show a message when comments are turned off....
I will submit a PR shortly. Does this approach sound reasonable?

2026-08-03 18:36 UTC, unixfox approved these changes
Good after resolving the merge conflicts.

2026-08-03 19:17 UTC, Fijxu commented
Everything in this PR remains the same, except for https://github.com/iv-org/invidious/pull/4051/commits/79f29780a431a57f532d087b960707d4a88414e8 which downstreams a fix to find if the comments are disabled or not, since the Innertube structure changed after this PR was opened.

https://git.nadeko.net/Fijxu/invidious/commit/36ac67610d1e52df731a21525fac966413541fa9

2026-08-03 19:18 UTC, merged

2026-08-03 19:22 UTC, Fijxu commented on src/invidious/views/watch.ecr
> +                                    <%= I18n.translate(locale, "comments_youtube_disabled_try_reddit_no_js") %>
Missing HTML.escape call here. I'll add a commit to `master` branch for this.